# This is a basic workflow to help you get started with Actions

name: Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        #qt_ver: [5.15.2,6.0.4,6.1.3]
        qt_ver: [5.15.2]
        qt_target: [desktop]
        #qt_arch: [win64_msvc2019_64, win32_msvc2019, win64_msvc2017_64, win32_msvc2017, win64_mingw81, win32_mingw81]
        qt_arch: [win64_msvc2019_64, win32_msvc2019, win64_mingw81, win32_mingw81]
        #exclude: 
          # - qt_ver: 5.9.8
          #   qt_arch: win32_mingw73
          # - qt_ver: 5.12.6
          #   qt_arch: win32_mingw53
        include:
          - qt_arch: win64_mingw81
            msvc_arch: x64
          - qt_arch: win32_mingw81
            msvc_arch: x86
          - qt_arch: win64_msvc2019_64
            msvc_arch: x64
          - qt_arch: win32_msvc2019
            msvc_arch: x86
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          qmake
          lrelease zh_CN.ts
          nmake
