name: Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        # qt_ver: [5.15.2, 6.0.4, 6.1.2]
        qt_ver: [5.15.2]
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: |
          qmake
          make
      - name: Upload compile output
        uses: actions/upload-artifact@v2
        with:
          path: rdss
